### ISSUE TITLE
Couple of Issues

### ISSUE THREAD

**Issue by nmeed** [noobj2/Anki-Advanced-Review-Bottombar#23]
If I download the file and try to install it that way, I get this error:

<img width="400" alt="image" src="https://user-images.githubusercontent.com/37801365/130469197-63da53ec-660d-4322-b5ea-1f8f981da05e.png">

If I install it through Anki itself, oddly enough it actually works and installs, however if I try to access the settings, I get teh following error:

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.46 (94913ec2) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.16
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-08-23 17:48:05
Add-ons possibly involved: ⁨Advanced Review Bottom Bar⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/XXX/Library/Application Support/Anki2/addons21/1136455830/Settings.py", line 2505, in open_settings
    settings = SettingsMenu()
  File "/Users/XXX/Library/Application Support/Anki2/addons21/1136455830/Settings.py", line 482, in __init__
    self.mainWindow()
  File "/Users/XXX/Library/Application Support/Anki2/addons21/1136455830/Settings.py", line 510, in mainWindow
    self.createNinthTab()
  File "/Users/XXX/Library/Application Support/Anki2/addons21/1136455830/Settings.py", line 1929, in createNinthTab
    self.loadChaneLog()
  File "/Users/XXX/Library/Application Support/Anki2/addons21/1136455830/Settings.py", line 1946, in loadChaneLog
    with open(file, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/XXX/Library/Application Support/Anki2/addons21/1136455830\\changelog.html'

**Comment by noobj2** [comment]
hi
can you try this add-on and let me know if it works properly?
[Download add-on](https://gofile.io/d/xlkmZD)

**Comment by nmeed** [comment]
Works like a charm, thanks!

**Comment by nmeed** [comment]
Could you please upload the file again? It's not available anymore and your recent update is still giving me the same issue. 
Also, I prefer to use "large and colorful buttons" due to very slight preferences (sorry), but when I use it along with the skip button, on the right side of the "answer buttons field area (?)" there is a vertical scroll bar for some reason. Do you have any idea how I could remove that by any chance? Thanks.

**Comment by noobj2** [comment]
hey
didn't see that you reopened the issue -\_- sorry
you should have been able to install it without an issue cuz I corrected the add-on manifest in the next release.
and about "large and colorful buttons" add-on, I know that some of you prefer to use other add-ons to change the button designs and that's why I added "Button colors" option in the "Misc" tab (it disables everything related to review buttons so you can use whichever add-on you like without worrying about conflicts and messing things up in anki).
but about the vertical scroll bar: maybe changing the height of the skip button solves it (?) not sure about it tho (you can change the height of the skip button in "Buttons Sizes" tab by changing "Bottombar buttons height")

another solution: you can change the size of the buttons in "Button Sizes" tab and try to replicate the design of "Large and colorful buttons" yourself

**Comment by noobj2** [comment]
Added a new button called "Load Settings".
When you press it it'll open a folder in which there's a file named "Large and Colorful Buttons.json" select it and press ok.
disable Large and colorful buttons add-on and use ARBb to change the style of the buttons. 

Changed the settings in a way the would recreate the look of large and colorful buttons add-on.
hopefully by using this you can get rid of the scrollbars. this was all I could do about it so I'm closing the issue now
