### ISSUE TITLE
Redirect or Disable  Shortcuts for Hidden Buttons

### ISSUE THREAD

**Issue by adamhl8** [noobj2/Anki-Advanced-Review-Bottombar#25]
I really love this addon. Would it be possible to add a feature that redirects or disables shortcuts for hidden buttons? For example, I've hidden the Hard and Easy buttons. I'd like it so that no matter what shortcut key I press (2/3/4), the Good button is always pressed. Or alternatively, add an option that simply disables shortcuts for hidden buttons.

For a better idea of what I'm talking about, see this addon: https://github.com/lambdadog/passfail2

**Comment by noobj2** [comment]
that's an interesting idea.
thanks for the suggestion, I'll add that as an option when I get some free time.

**Comment by noobj2** [comment]
hey
I am updating my add-ons so I was going through user requests. When I was thinking about how to add what you requested I remembered why I wasn't messing with the shortcuts too much (I added shortcuts for my custom buttons but didn't add an option for customizing other shortcuts). The reason is a really amazing add-on which gives you full control over your shortcuts.

I looked at the [add-on page](https://ankiweb.net/shared/info/24411424) and the add-on author has added both of the features you asked for (you can set two shortcuts to do the same thing and you can also fully disable a shortcut if it's what you want).

but since the add-on doesn't have a settings menu, you'll have to set shortcuts manually in the config editor so I recommend you read the add-on description to see what you can do and also read [config.md](https://github.com/Liresol/anki-custom-shortcuts/blob/master/custom_shortcuts/config.md) page to see how you can use the add-on.

I'll close the issue now. If you had any other questions regarding this issue simply re-open the issue :)
