### ISSUE TITLE
[FEATURE REQUEST] Adding ease count in the info bar?

### ISSUE THREAD

**Issue by sevazre** [noobj2/Anki-Advanced-Review-Bottombar#6]
Would it be possible to add these counts to the info bar? It would be nice so as to identify and subsequently mark the toughest cards while studying them.
![New stats in the bar](https://user-images.githubusercontent.com/43146889/87847330-a3cf0a00-c8d7-11ea-9bba-4f1919a9d1b5.png)

**Comment by noobj2** [comment]
Done!
you can't update it using anki desktop tho. you should manually download this repository and replace the files in add-on folder with these new files.
haven't added a button in settings to disable this, so when you update it, you won't be able to disable it.
it counts all reviews (learn/re-learn included) that's why Lapses aren't equal to the easy count. i'll probably add an option to change that tho.
any suggestion about how to improve is appreciated 😃

**Comment by sevazre** [comment]
Thanks! It's exactly what I was looking for 😁
