### ISSUE TITLE
can't use Hide Buttons while disabling Color buttons

### ISSUE THREAD

**Issue by Hosseingsd** [noobj2/Anki-Advanced-Review-Bottombar#68]
Hello and thank you for your addon. 
(after applying changes I restart Anki and before restarting I disabled all other addons to make sure it's not inter-addon conflict) 

Problem: If I disable button colors color in the misc tab, then hiding buttons does not work: 

![problem](https://github.com/noobj2/Anki-Advanced-Review-Bottombar/assets/110593678/559c553d-07e6-4fa1-956d-b7d1b297cff2)

**Comment by noobj2** [comment]
hey
Thanks for the report.

This is expected behaviour since disabling the button colors removes all the button stylings of ARBb add on. This enables uses to use other button styling add-ons while also using other features of this add-on.
However if you want to use default style button while being able to hide hard and easy buttons, you can click on Load Settings in the settings menu and the style of the buttons will be like the stock buttons (with some colors on the answer button texts).
If you don't like colored text inside the buttons, you can go to colors tab and enable colors, and choose white as color of the text in the color picker window.

But I feel like I should change the title of that item in the settings menu to "Button Styling".
I'll change the title to button styling to better describe what it does -\_-

And I've also noticed that the button border radius doesn't work for default buttons, I'll also fix that in the next update so you could duplicate that button style without having to disable "Button Colors" at all.

I'm sorry for the late response I've been pretty busy with my exams. And If you have any other question I'll be more than happy to answer you :D
