### ISSUE TITLE
New button hook (and Auto Ease Factor compatibility).

### ISSUE THREAD

**Issue by brownbat** [noobj2/Anki-Advanced-Review-Bottombar#9]
Not sure if this will help you or not, but I added a hook to Anki to help all the add-on developers who are editing buttons, like my add-on, yours, and like a half dozen others I've seen: 

[reviewer_will_init_answer_buttons hook](https://github.com/ankitects/anki/blob/a8eba9d3419d75e3add2e24580e2eb3d78688044/qt/tools/genhooks_gui.py#L61)

A few people have asked me to work on compatibility between your ARBB and my add-on, Auto Ease Factor. Mine is mainly a scheduling algorithm, but it has a two-button mode that I think does weird things when combined with yours.

I haven't really been able to dig in to figure out how hard it would be to make them compatible yet... still looking... but welcome any ideas.
[Auto Ease Factor](https://github.com/brownbat/autoEaseFactor)

(On the other hand, people can disable my two-button mode in settings and still get the scheduling benefits -- maybe that's the simple workaround for now.)

**Comment by noobj2** [comment]
hey. I'm really sorry, couldn't answer you sooner -_-

about the compatibility, I have tried to make my add-on compatible with other add-ons that are trying to change "Reviewer._answerButtons" functions. had no luck.
because in order for my add-on to function properly, it needs to fully change "Reviewer._answerButtons" function and when I created the add-on, accomplishing that level of customizability just wasn't possible through the hooks. so for now, and till I find some free time to work on the code and see if I can use hooks/monkey patching method instead of fully replacing the "Reviewer._answerButtons" function, users should choose between two-button mode and my add-on. they can't coexist for now :(

**Comment by brownbat** [comment]
Totally understand, I know a lot of the add-ons are passion projects that people do on the side, on top of day jobs. 

If it helps, when I finally rewrote my two-button mode to use the new hook, I was able to cut my lines of code by something crazy like 90%. If you ever do take a shot at a refactor, it's there for you, hopefully will be some help.

Best of luck!

**Comment by noobj2** [comment]
it's been 2 years -\_-
and no user has opened an issue about auto ease factor compatibility 
I'll close the issue not -\_-
